name: blue
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.5.0"

dependencies:
  charset_converter: ^2.0.0
  cupertino_icons: ^1.0.3
  esc_pos_bluetooth:
    path: ../../
  esc_pos_utils:
    git:
      url: https://github.com/alfas-hancod/esc_pos_utils
      ref: master
  flutter:
    sdk: flutter
  image: ^4.5.4
  intl: ^0.20.2
  oktoast: ^3.0.0
  path_provider: ^2.0.2
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo216.png
    - assets/logo222.png
    - assets/rabbit_black.jpg
